name: Feature Request / Improvement
description: Mô tả tính năng hoặc cải thiện — điền càng chi tiết càng tốt.
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã đóng góp! Hãy điền các thông tin dưới đây để team có thể hiểu và xử lý nhanh hơn.

  - type: input
    id: summary
    attributes:
      label: Description
      description: Giải thích ngắn gọn về feature / cải tiến
      placeholder: 'Ví dụ: Enhance the livestream experience by improving the comment viewing functionality'
    validations:
      required: true

  - type: textarea
    id: acceptance_text
    attributes:
      label: Acceptance Criteria (miêu tả)
      description: Viết mô tả/ghi chú cho acceptance criteria nếu cần
      placeholder: |
        - Comments appear instantly (<1s delay) without page refresh
        - Smooth, consistent synchronization across all viewers
    validations:
      required: false

  - type: checkboxes
    id: acceptance_checks
    attributes:
      label: Acceptance Criteria (checkbox)
      description: Đánh dấu những tiêu chí đã thỏa
      options:
        - label: Comments appear instantly (<1s delay) without page refresh
        - label: Smooth, consistent synchronization across all viewers
        - label: Fully responsive on desktop
        - label: Backward compatible with existing livestream modules

  - type: dropdown
    id: priority
    attributes:
      label: Mức độ ưu tiên
      description: Chọn mức độ quan trọng
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true
