name: Feature Request / Improvement
description: Mô tả tính năng hoặc cải thiện bạn muốn — càng cụ thể càng tốt.
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã đóng góp! Hãy điền các thông tin bên dưới để giúp team tái tạo và xử lý nhanh hơn.

  - type: input
    id: description
    attributes:
      label: Description
      description: Giải thích chi tiết về tính năng / cải thiện
      placeholder: 'Ví dụ: Enhance the livestream experience by improving the comment viewing functionality'
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Danh sách các tiêu chí để chấp nhận feature này
      placeholder: |
        - Comments appear instantly (<1s delay) without page refresh
        - Smooth, consistent synchronization across all viewers
        - Fully responsive on desktop
        - Backward compatible with existing livestream modules
    validations:
      required: true

  - type: checkboxes
    id: extras
    attributes:
      label: Các tuỳ chọn bổ sung (nếu có)
      options:
        - label: Thêm bản dịch tiếng Việt
          value: translate_vi
        - label: Hỗ trợ theme tối / sáng
          value: theme_support
        - label: Tương thích thiết bị di động
          value: mobile_compatible

  - type: dropdown
    id: priority
    attributes:
      label: Mức độ ưu tiên
      options:
        - label: Low
          value: low
        - label: Medium
          value: medium
        - label: High
          value: high
        - label: Critical
          value: critical
