name: Feature Request / Improvement
description: Mô tả tính năng hoặc cải thiện bạn muốn — càng cụ thể càng tốt.
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã đóng góp! Hãy điền các thông tin bên dưới để giúp team tái tạo và làm việc nhanh hơn.

  - type: input
    id: summary
    attributes:
      label: Description
      description: Giải thích ngắn gọn về feature / cải thiện
      placeholder: 'Ví dụ: Enhance the livestream experience by improving the comment viewing functionality'
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Danh sách các tiêu chí để chấp nhận feature này
      placeholder: |
        - Comments appear instantly (<1s delay) without page refresh
        - Smooth, consistent synchronization across all viewers
        - Fully responsive on desktop
        - Backward compatible with existing livestream modules
    validations:
      required: true

  - type: checkboxes
    id: extras
    attributes:
      label: Các tuỳ chọn bổ sung (nếu có)
      options:
        - Thêm bản dịch tiếng Việt
        - Hỗ trợ theme tối / sáng
        - Tương thích thiết bị di động

  - type: dropdown
    id: priority
    attributes:
      label: Mức độ ưu tiên
      options:
        - Low
        - Medium
        - High
        - Critical
